# (PART) Using bookdown {-}

# Getting Started

We recommend reading the online version of this template rather than the source files while you are getting started.

## With Git (Recommended)

The best way to get started with with this template is through forking the `bookdown-thesis-template` on GitHub:

1. Install R, RStudio, bookdown, and the other R packages on your computer.
2. Create a GitHub account.
3. Set up Git on your computer using [RStudio](https://happygitwithr.com) (recommended) or [GitHub Desktop](https://desktop.github.com).
4. [Fork](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo) the GitHub repository https://github.com/mccarthy-m-g/bookdown-thesis-template, then clone it to your computer using [RStudio](https://support.rstudio.com/hc/en-us/articles/200532077-Version-Control-with-Git-and-SVN) (recommended) or [GitHub Desktop](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/cloning-and-forking-repositories-from-github-desktop).
5. Open the `bookdown-thesis-template` repository you cloned in RStudio by double-clicking `bookdown-thesis-template.Rproj`.
6. Open the R Markdown file `index.Rmd` and click the button Build Book on the Build tab of RStudio to render the template.

## Without Git

The easiest way for beginners to get started with this template is through downloading the `bookdown-thesis-template` on GitHub:

1. Install R, RStudio, bookdown, and the other R packages on your computer.
2. Download the GitHub repository https://github.com/mccarthy-m-g/bookdown-thesis-template as a Zip file, then unzip it locally.
3. Open the `bookdown-thesis-template` repository you downloaded in RStudio by double-clicking `bookdown-thesis-template.Rproj`.
4. Open the R Markdown file `index.Rmd` and click the button Build Book on the Build tab of RStudio to render the template.
