--- 
title: "Bookdown Thesis Template"
shorttitle: "Bookdown Thesis Template"

author:
# Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
# You can format your author list in several ways; below are some examples:
- |
  First Last^[Corresponding author information],
  University,  
  Contributor Roles:  
  - Conceptualization  
  - Project Administration
- |
  First Last,
  University^[CRediT Contributor Roles]
- "First Last^[University, CRediT Contributor Roles]"

date: "`r format(Sys.Date(), '%B %d %Y')`"

site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: ["references.bib", "r-packages.bib"]
biblio-style: "apa.csl"
link-citations: yes

github-repo: mccarthy-m-g/bookdown-thesis-template

favicon: www/favicon.ico
cover-image: 
description: "A bookdown thesis template for writing your thesis."
---

```{r setup, include=FALSE}
renv::snapshot()
```

# Welcome {-}

This is the online version of *The Bookdown Thesis Template*.

The Bookdown Thesis Template is a comprehensive bookdown template, covering everything you need to write, edit, and disseminate your thesis. [bookdown](https://bookdown.org) is is an [open-source R package](https://github.com/rstudio/bookdown) that facilitates writing books and long-form articles or reports with R Markdown. Features include:

- Generate printer-ready books and ebooks from R Markdown documents.
- A markup language easier to learn than LaTeX, and to write elements such as section headers, lists, quotes, figures, tables, and citations.
- Multiple choices of output formats: PDF, LaTeX, HTML, EPUB, and Word.
- Possibility of including dynamic graphics and interactive applications (HTML widgets and Shiny apps).
- Support a wide range of languages: R, C/C++, Python, Fortran, Julia, Shell scripts, and SQL, etc.
- LaTeX equations, theorems, and proofs work for all output formats.
- Can be published to GitHub, bookdown.org, Netlify, and any web servers.
- Integrated with the RStudio IDE.

You can learn more about using bookdown to write your thesis in the short book [*bookdown: Authoring Books and Technical Documents with R Markdown*](https://bookdown.org/yihui/bookdown/).

If you do not wish to publish your thesis to its own website, the R package [papaja](https://crsh.github.io/papaja_man/customizations.html#writing-dissertations) might be better for you.

## License {-}

This template is licensed to you under the [MIT License](https://github.com/mccarthy-m-g/bookdown-thesis-template/blob/master/LICENSE).
